markdown: rdiscount
permalink: /:year/:month/:day/:title.html
url: http://www.lizhaozhong.info
name: JasonLe's Blog |HomePage
author: JasonLe
email: ldm5235@gmail.com
duoshuo: lzz5235 
beian:
weibo: 1911215851 
github: lzz5235
pygments: true
safe: true
paginate: 20
about: "这里是JasonLe的个人博客。擅长C/C++编程，熟悉Qt，ACE框架编程，熟悉类Unix系统，熟悉Fedora Ubuntu 等类Unix系统，熟悉Shell编程，熟悉Sybase，Mysql数据库，及相关操作。熟悉Hadoop相关集群架设，对于云计算，与分布式存储

有强烈兴趣。对设计模式，系统结构有较熟悉的研究。"
